// TODO: find a better way to save rulesType for function restoration
// missing cards: M2 (Lightning Strike), M38 (Golden Frog), M89 (Pygmy Leaf Chameleon)
let config_M = {
	"M0": {
		"name": "",
		"pack": "",
		"number": 0,
		"cardType": "",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "",
		"flavorText": "",
		"image": null,
	},
	"M1": {
		"name": "Camouflage",
		"pack": "Madagascar",
		"number": 1,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["blue"],
			"top": ["orange", "yellow"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5",
		"flavorText": "Great defense - animals blend in to hide.",
		"image": null,
	},
	"M2": {
		"name": "Fresh Spring",
		"pack": "Madagascar",
		"number": 2,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["orange", "red", "blue"],
			"top": [],
			"bottom": ["blue", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-4",
		"flavorText": "A quick drink refreshes.",
		"image": null,
	},
	"M3": {
		"name": "Warning Sign",
		"pack": "Madagascar",
		"number": 3,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange"],
			"right": ["orange", "yellow"],
			"top": ["orange", "yellow"],
			"bottom": ["yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-ENEMYHAND",
		"flavorText": "Birds take flight giving warning that something big is on its way.",
		"image": null,
	},
	"M4": {
		"name": "Vacant Cave",
		"pack": "Madagascar",
		"number": 4,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": [],
			"top": ["red"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-10",
		"flavorText": "Great place to hide ... hope it's empty!",
		"image": null,
	},
	"M6": {
		"name": "Swarm",
		"pack": "Madagascar",
		"number": 6,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": [],
			"right": ["yellow", "blue"],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "blue"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-TROPHIC1MULT2",
		"flavorText": "There's strength in numbers.",
		"image": null,
	},
	"M7": {
		"name": "Disguise",
		"pack": "Madagascar",
		"number": 7,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["orange"],
			"top": ["orange", "yellow"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-2-5",
		"flavorText": "To be invisible, blend in.",
		"image": null,
	},	
	"M8": {
		"name": "Armour",
		"pack": "Madagascar",
		"number": 8,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": [],
			"top": ["orange"],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-3-5",
		"flavorText": "Crusty shell protects so well!",
		"image": null,
	},	
	"M9": {
		"name": "Heavy Storm",
		"pack": "Madagascar",
		"number": 9,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": [],
			"right": ["orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFTIE",
		"flavorText": "All creatures, big and small, take cover in heavy weather.",
		"image": null,
	},	
	"M10": {
		"name": "Stridulation",
		"pack": "Madagascar",
		"number": 10,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "red"],
			"right": ["red", "orange"],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-3-REUSECARD",
		"flavorText": "The vibrating of spines to make a resping sound scares some predators away.",
		"image": null,
	},	
	"M11": {
		"name": "Food Stash",
		"pack": "Madagascar",
		"number": 11,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": ["red", "orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-7-REUSECARD",
		"flavorText": "Quick snack gives extra energy.",
		"image": null,
	},	
	"M12": {
		"name": "Toxic",
		"pack": "Madagascar",
		"number": 12,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["yellow"],
			"right": [],
			"top": ["red", "yellow"],
			"bottom": ["yellow", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-BASEENERGY",
		"flavorText": "Some species acquire toxins through their diet, making them poisonous and yucky-tasting. The Mantella baroni snacks on ants.",
		"image": null,
	},	
	"M13": {
		"name": "Rain",
		"pack": "Madagascar",
		"number": 13,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": [],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-REUSECARD",
		"flavorText": "Tsy misy ala, tsy misy rano, tsy misy vary!",
		"image": null,
	},	
	"M14": {
		"name": "Hiding Spot",
		"pack": "Madagascar",
		"number": 14,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "orange"],
			"right": ["orange", "blue"],
			"top": ["orange", "yellow"],
			"bottom": ["blue", "yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-3-DRAWCARD-1",
		"flavorText": "Lie low and keep quiet until trouble passes by...",
		"image": null,
	},	
	"M15": {
		"name": "Sticky Web Trap",
		"pack": "Madagascar",
		"number": 15,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["orange", "blue"],
			"top": ["yellow", "orange", "blue"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFENEMYUSELESSBOOSTS",
		"flavorText": "Gumbed up in a spider's sticky web.",
		"image": null,
	},	
	"M16": {
		"name": "Up a Tree",
		"pack": "Madagascar",
		"number": 16,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["red", "yellow"],
			"top": ["orange", "red", "yellow"],
			"bottom": ["yellow", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-NOTFIRSTBOOST-5",
		"flavorText": "Out of harm's reach?",
		"image": null,
	},	
	"M17": {
		"name": "Full Moon",
		"pack": "Madagascar",
		"number": 17,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"],
			"top": ["yellow", "orange"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-6",
		"flavorText": "Moon light, shine bright. Light the earth for the hunt tonight.",
		"image": null,
	},	
	"M18": {
		"name": "Fangs!",
		"pack": "Madagascar",
		"number": 18,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"],
			"top": ["yellow"],
			"bottom": ["yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-2-3",
		"flavorText": "Sharp teeth --- big bite! Fangs give Turf War advantage.",
		"image": null,
	},	
	"M19": {
		"name": "Brute Force",
		"pack": "Madagascar",
		"number": 19,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["orange"],
			"right": ["orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-3-3",
		"flavorText": "It helps to be big and strong.",
		"image": null,
	},	
	"M20": {
		"name": "Ruckuss!",
		"pack": "Madagascar",
		"number": 20,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "red"],
			"right": ["orange", "yellow"],
			"top": ["orange", "blue"],
			"bottom": ["yellow", "red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-4",
		"flavorText": "Make crazy noise to win the day.",
		"image": null,
	},	
	"M21": {
		"name": "Symbiosis",
		"pack": "Madagascar",
		"number": 21,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["blue"],
			"right": ["orange", "yellow"],
			"top": ["blue"],
			"bottom": ["orange", "yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFADDENEMYECO",
		"flavorText": "Wild collaboration. These clever frogs have a wet home and ready bug supply thanks to the pitcher plant.",
		"image": null,
	},	
	"M22": {
		"name": "Healing Plant",
		"pack": "Madagascar",
		"number": 22,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["blue"],
			"right": ["blue"],
			"top": ["blue"],
			"bottom": ["blue"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-1-3",
		"flavorText": "Rosy periwinkle, found only in Madagascar, is considered a miracle plant.",
		"image": null,
	},	
	"M23": {
		"name": "Nocturnal Instinct",
		"pack": "Madagascar",
		"number": 23,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["red"],
			"top": ["red"],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-7-ADDTROPHIC-4-5",
		"flavorText": "Looking for a midnight snack!",
		"image": null,
	},	
	"M24": {
		"name": "Super Smell",
		"pack": "Madagascar",
		"number": 24,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": [],
			"right": ["red"],
			"top": [],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-10",
		"flavorText": "Sniff. Sniff! What smells? Oh, it's my tail!",
		"image": null,
	},	
	"M25": {
		"name": "Super Speed",
		"pack": "Madagascar",
		"number": 25,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["purple"],
			"right": ["purple"],
			"top": ["purple"],
			"bottom": ["purple"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-15",
		"flavorText": "Go fast to catch your prey or get away!",
		"image": null,
	},
	"M26": {
		"name": "Golden Bamboo Lemur",
		"pack": "Madagascar",
		"number": 26,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Hapalemur aureus",
		"rarity": "Vanishing",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 12,
		"points": 10,
		"level": 4,
		"rulesType": "TURFNOBOOST",
		"flavorText": "One of the world's most endangered. GBL eats daily - 500g of bamboo containing 12 times the amount of cyanide lethal to most animals.",
		"image": null,
	},
	"M27": {
		"name": "Hawk Moth",
		"pack": "Madagascar",
		"number": 27,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Xanthopan morganii praedicta",
		"rarity": "Common",
		"borders": {
			"left": [],
			"right": ["red"]
			"top": [],
			"bottom": ["red"],
		},
		"energy": 13,
		"points": 13,
		"level": 4,
		"rulesType": "",
		"flavorText": "Super-fast flyers and symbiotic with comet orchid. Darwin predicted their existence before they were known.",
		"image": null,
	},
	"M28": {
		"name": "Fossa",
		"pack": "Madagascar",
		"number": 28,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Cryptoprocta ferox",
		"rarity": "Endangered",
		"borders": {
			"left": ["purple"],
			"right": []
			"top": ["purple"],
			"bottom": ["purple"],
		},
		"energy": 14,
		"points": 11,
		"level": 4,
		"rulesType": "FEROCITY-6",
		"flavorText": "One of the world's weirdest - and Madagascar's most ferocious - predators. Said to have a nose like a dog's, teeth like a leopard's and whiskers like an otter's.",
		"image": null,
	},
	"M29": {
		"name": "Hawksbill Sea Turtle",
		"pack": "Madagascar",
		"number": 29,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Eretmochelys imbricata",
		"rarity": "Vanishing",
		"borders": {
			"left": [],
			"right": ["purple", "red"]
			"top": ["purple", "red"],
			"bottom": [],
		},
		"energy": 13,
		"points": 9,
		"level": 4,
		"rulesType": "MORPH-4",
		"flavorText": "This ocean swimmer loves the taste of sea sponges. Mind the beak!",
		"image": null,
	},
	"M30": {
		"name": "Madagascar Fish Eagle",
		"pack": "Madagascar",
		"number": 30,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Haliaeetus vociferoides",
		"rarity": "Vanishing",
		"borders": {
			"left": ["red", "purple"],
			"right": ["purple", "red"]
			"top": [],
			"bottom": ["red", "purple"],
		},
		"energy": 14,
		"points": 12,
		"level": 4,
		"rulesType": "",
		"flavorText": "Close relative of the bald eagle - one of the most endangered raptors in the world. Loud, measured call: Wha ... wah ... wah ...",
		"image": null,
	},
	"M31": {
		"name": "Golden Crowned Lemur",
		"pack": "Madagascar",
		"number": 31,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Propithecus tattersalli",
		"rarity": "Vanishing",
		"borders": {
			"left": ["red", "purple"],
			"right": []
			"top": ["red", "purple"],
			"bottom": ["red", "purple"],
		},
		"energy": 9,
		"points": 15,
		"level": 4,
		"rulesType": "",
		"flavorText": "One of the most endangered lemurs and fady to harm. Grooms its (and friends') fur with six lower teeth that stick out to form a funky comb.",
		"image": null,
	},
	"M32": {
		"name": "Ploughshare Tortoise",
		"pack": "Madagascar",
		"number": 32,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Geochelone yniphora",
		"rarity": "Endangered",
		"borders": {
			"left": ["red", "purple"],
			"right": ["red", "purple"]
			"top": ["red", "purple"],
			"bottom": [],
		},
		"energy": 10,
		"points": 10,
		"level": 4,
		"rulesType": "NEST-6",
		"flavorText": "In wrestling matches to win a mate, these turtles use their \"plow\" to flip over opponents.",
		"image": null,
	},
	"M33": {
		"name": "Tomato Frog",
		"pack": "Madagascar",
		"number": 33,
		"cardType": "Species",
		"speciesType": "Amphibian",
		"speciesName": "Dyscophus antongili",
		"rarity": "",
		"borders": {
			"left": [],
			"right": ["red", "purple"]
			"top": ["red", "purple"],
			"bottom": ["red", "purple"],
		},
		"energy": 13,
		"points": 6,
		"level": 4,
		"rulesType": "DEFEND-3-4",
		"flavorText": " Red like a ripe tomato. As a defense, it secretes a toxic ooze.",
		"image": null,
	},
	"M34": {
		"name": "Giant Leaf-tailed Gecko",
		"pack": "Madagascar",
		"number": 34,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Uroplatus fimbriatus",
		"rarity": "Common",
		"borders": {
			"left": ["red", "purple"],
			"right": []
			"top": ["red", "purple"],
			"bottom": [],
		},
		"energy": 11,
		"points": 14,
		"level": 4,
		"rulesType": "",
		"flavorText": "Gecko with perfect tree camouflage. Bark-like skin, large eyes, no eye lids, a flip-top head and leaf-like tail.",
		"image": null,
	},
	"M35": {
		"name": "Nile Crocodile",
		"pack": "Madagascar",
		"number": 35,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Crocodylus niloticus",
		"rarity": "Common",
		"borders": {
			"left": [],
			"right": ["red", "purple"]
			"top": [],
			"bottom": ["red", "purple"],
		},
		"energy": 15,
		"points": 8,
		"level": 4,
		"rulesType": "",
		"flavorText": "One tough and hungry crock - where did that bird go? (Burp!)",
		"image": null,
	},
	"M36": {
		"name": "Giant-striped Mongoose",
		"pack": "Madagascar",
		"number": 36,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Galidictis grandidieri",
		"rarity": "Endangered",
		"borders": {
			"left": ["red", "purple"],
			"right": []
			"top": ["red", "purple"],
			"bottom": ["red", "purple"],
		},
		"energy": 10,
		"points": 9,
		"level": 4,
		"rulesType": "TURFSPECIES-REPTILE-4",
		"flavorText": "Nocturnal and crepuscular - active at night and at twilight.",
		"image": null,
	},
	"M37": {
		"name": "Malagasy Ring-tailed Mongoose",
		"pack": "Madagascar",
		"number": 37,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Galidia elegans",
		"rarity": "Rare",
		"borders": {
			"left": [],
			"right": ["red", "purple"]
			"top": [],
			"bottom": ["red", "purple"],
		},
		"energy": 10,
		"points": 11,
		"level": 4,
		"rulesType": "TURFSPECIES-REPTILE-4",
		"flavorText": "Diurnal and gregarious - active and playful during the day.",
		"image": null,
	},
	"M39": {
		"name": "Commerson's Leaf-nosed Bat",
		"pack": "Madagascar",
		"number": 39,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Hipposideros commersoni",
		"rarity": "Common",
		"borders": {
			"left": ["purple"],
			"right": ["red"]
			"top": ["purple"],
			"bottom": ["purple"],
		},
		"energy": 11,
		"points": 12,
		"level": 4,
		"rulesType": "TURFDIAGONAL",
		"flavorText": "Holy bat-nose! With a wingspan of nearly 2 feet, it's one of the largest insectivors in Africa.",
		"image": null,
	},
	"M40": {
		"name": "Hairy-eared Dwarf Lemur",
		"pack": "Madagascar",
		"number": 40,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Allocebus trichotis",
		"rarity": "Vanishing",
		"borders": {
			"left": ["purple"],
			"right": ["purple"]
			"top": ["purple"],
			"bottom": ["purple"],
		},
		"energy": 7,
		"points": 17,
		"level": 4,
		"rulesType": "",
		"flavorText": "One of the rarest, smallest - and cutest - primates on the planet, once thought extinct, this lemur was \"rediscovered\" with the help of a Malagasy local.",
		"image": null,
	},
	"M41": {
		"name": "Alluaudia Spiny Plant",
		"pack": "Madagascar",
		"number": 41,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Alluaudia montagnacii",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["yellow"],
			"bottom": ["yellow"],
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "PLANT-TROPHICCOUNT3",
		"flavorText": "A prickly perch.",
		"image": null,
	},
	"M42": {
		"name": "Comet Orchid",
		"pack": "Madagascar",
		"number": 42,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Angraecum sesquipedale",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "PLANT-HAWKMOTH",
		"flavorText": "",
		"image": null,
	},
	"M43": {
		"name": "Dutchman's Pipe",
		"pack": "Madagascar",
		"number": 43,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Aristolochia",
		"rarity": "Common",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "PLANT-TROPHICCOUNT2",
		"flavorText": "The flowers of most Aristolochia emit a powerful stench - smells like rotting meat. Pee-eew!",
		"image": null,
	},
	"M44": {
		"name": "Carnivorous Pitcher Plant",
		"pack": "Madagascar",
		"number": 44,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Nepenthes madagascariensis",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"]
			"top": ["yellow", "orange"],
			"bottom": ["yellow", "orange"],
		},
		"energy": 0,
		"points": 0,
		"level": [0,2],
		"rulesType": "PLANT-PITCHER", 
		"flavorText": "The pretty plant is deadly to bugs. Digests insects for a meal.",
		"image": null,
	},
	"M45": {
		"name": "Voantany",
		"pack": "Madagascar",
		"number": 45,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Hydnora esculenta",
		"rarity": "Rare",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 0,
		"points": 3,
		"level": 0,
		"rulesType": "PLANT-SUNRISEDRAW",
		"flavorText": "Lemurs' favorite. Extremely rare and known as \"fruit of the earth.\"",
		"image": null,
	},
	"M46": {
		"name": "Grandidier Baobab",
		"pack": "Madagascar",
		"number": 46,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Adansonia grandidieri",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["yellow"],
			"bottom": ["yellow"],
		},
		"energy": 0,
		"points": 3,
		"level": [0,1,4],
		"rulesType": "PLANT",
		"flavorText": "African tree of life. Sacred.",
		"image": null,
	},
	"M47": {
		"name": "White Lotus",
		"pack": "Madagascar",
		"number": 47,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Nymphaea lotus",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 0,
		"points": 5,
		"level": 0,
		"rulesType": "PLANT-ADJBOOST-1",
		"flavorText": "An old and evolutionarily primitive beauty.",
		"image": null,
	},
	"M48": {
		"name": "Tamarind Tree",
		"pack": "Madagascar",
		"number": 48,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Tamarindus indica",
		"rarity": "Common",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["yellow"],
			"bottom": ["yellow"],
		},
		"energy": 0,
		"points": 3,
		"level": 0,
		"rulesType": "PLANT-ADJBOOST-3",
		"flavorText": "Lemur catta's favorite.",
		"image": null,
	},
	"M49": {
		"name": "Travelers Palm",
		"pack": "Madagascar",
		"number": 49,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Ravenala madagascariensis",
		"rarity": "Common",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 0,
		"points": 4,
		"level": 0,
		"rulesType": "PLANT-ADJBOOST-2",
		"flavorText": "A welcome sign.",
		"image": null,
	},
	"M50": {
		"name": "Giant Bamboo",
		"pack": "Madagascar",
		"number": 50,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Cathariostachys madagascariensis",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 0,
		"points": 4,
		"level": 0,
		"rulesType": "PLANT-GIANTBAMBOO",
		"flavorText": "High in protein as well as cyanide.",
		"image": null,
	},
	"M51": {
		"name": "Indri",
		"pack": "Madagascar",
		"number": 51,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Indri indri",
		"rarity": "Endangered",
		"borders": {
			"left": ["blue"],
			"right": ["yellow", "blue"]
			"top": ["blue"],
			"bottom": ["yellow", "blue"],
		},
		"energy": 6,
		"points": 3,
		"level": 1,
		"rulesType": "TURFMOMENTUM",
		"flavorText": "\"There it is.\"",
		"image": null,
	},
	"M52": {
		"name": "Verreaux's Sifaka",
		"pack": "Madagascar",
		"number": 52,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Propithecus verreauxii",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["blue"]
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "blue"],
		},
		"energy": 9,
		"points": 5,
		"level": 1,
		"rulesType": "TURFINVADETROPHIC-2-3",
		"flavorText": "Great gliders. Capable of making giant jumps through trees - leaps of 30 ft are not uncommon!",
		"image": null,
	},
	"M53": {
		"name": "Woolly Lemur",
		"pack": "Madagascar",
		"number": 53,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Avahi laniger",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["yellow", "blue"]
			"top": [],
			"bottom": ["yellow", "blue"],
		},
		"energy": 8,
		"points": 6,
		"level": 1,
		"rulesType": "",
		"flavorText": "Out at night with eyes so bright.",
		"image": null,
	},
	"M54": {
		"name": "Flat-tailed Tortoise",
		"pack": "Madagascar",
		"number": 54,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Pyxix planicauda",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["yellow", "blue"]
			"top": ["yellow", "blue"],
			"bottom": [],
		},
		"energy": 7,
		"points": 5,
		"level": 1,
		"rulesType": "TURFINVADETROPHIC-1-5",
		"flavorText": "Known locally as Kapidolo (ghost turtle).",
		"image": null,
	},
	"M55": {
		"name": "Katydid",
		"pack": "Madagascar",
		"number": 55,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Aspidonotus spinosus",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["blue"]
			"top": [],
			"bottom": ["yellow", "blue"],
		},
		"energy": 10,
		"points": 5,
		"level": 1,
		"rulesType": "",
		"flavorText": "What can a bug do to hide? Make like a tree and leaf!",
		"image": null,
	},
	"M56": {
		"name": "Spider Tortoise",
		"pack": "Madagascar",
		"number": 56,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Pyxis arachnoides",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue"]
			"top": ["yellow", "blue"],
			"bottom": [],
		},
		"energy": 10,
		"points": 5,
		"level": 1,
		"rulesType": "TURFDIAGONAL",
		"flavorText": "Tortoises are sacred and lucky! It is fady to harm them.",
		"image": null,
	},
	"M57": {
		"name": "Fire Millipede",
		"pack": "Madagascar",
		"number": 57,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Aphistogoniulus",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["blue"]
			"top": [],
			"bottom": ["yellow", "blue"],
		},
		"energy": 9,
		"points": 5,
		"level": 1,
		"rulesType": "TURFFEROCITY-4",
		"flavorText": "Ready ... Aim ... Millipede!",
		"image": null,
	},
	"M58": {
		"name": "Madagascar Hissing Cockroach",
		"pack": "Madagascar",
		"number": 58,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Gromphadorhina portentosa",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["yellow", "blue"]
			"top": ["yellow", "blue"],
			"bottom": [],
		},
		"energy": 12,
		"points": 2,
		"level": 1,
		"rulesType": "",
		"flavorText": "Giant cockroaches that hisssssss. Hisssssss. Hissssssssssssssssss.",
		"image": null,
	},
	"M59": {
		"name": "Comet Moth",
		"pack": "Madagascar",
		"number": 59,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Argema mittrei",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 8,
		"points": 5,
		"level": 1,
		"rulesType": "MORPH-1",
		"flavorText": "These gentle flyers have up to 8-inch wing spans. Tres bizarre: Adult comet moths have no mouths!",
		"image": null,
	},
	"M60": {
		"name": "Giraffe-necked Weevil",
		"pack": "Madagascar",
		"number": 60,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Trachelophorus giraffa",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["blue", "yellow"]
			"top": ["blue", "yellow"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 6,
		"points": 4,
		"level": 1,
		"rulesType": "SUNRISE-MIGRATE-2",
		"flavorText": "",
		"image": null,
	},
	"M61": {
		"name": "Clear-winged Butterfly",
		"pack": "Madagascar",
		"number": 61,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Undefined",
		"rarity": "Common",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 8,
		"points": 4,
		"level": 1,
		"rulesType": "TURFINVADETROPHIC-3-8",
		"flavorText": "Field agents report in: Help Xeko learn the scientific name for this fancy flyer.",
		"image": null,
	},
	"M62": {
		"name": "Yellow-line Caterpillar",
		"pack": "Madagascar",
		"number": 62,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Lymantriidae",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue", "yellow"]
			"top": ["blue"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 8,
		"points": 6,
		"level": 1,
		"rulesType": "",
		"flavorText": "This caterpillar eats and eats, munching leaves for a treat.",
		"image": null,
	},
	"M63": {
		"name": "Orange Pill Millipede",
		"pack": "Madagascar",
		"number": 63,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Diplopoda",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["yellow"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 8,
		"points": 6,
		"level": 1,
		"rulesType": "",
		"flavorText": "Two pairs of legs on every ring, makes me so happy I could sing!",
		"image": null,
	},
	"M64": {
		"name": "Radiated Tortoise",
		"pack": "Madagascar",
		"number": 64,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Geochelone radiata",
		"rarity": "Rare",
		"borders": {
			"left": ["blue"],
			"right": ["blue", "yellow"]
			"top": ["blue"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 10,
		"points": 5,
		"level": 1,
		"rulesType": "",
		"flavorText": "One of the rarest tortoises. Rod's favorite - a true star.",
		"image": null,
	},
	"M65": {
		"name": "Gold Tortoise Beetle",
		"pack": "Madagascar",
		"number": 65,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Cassidinae",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["yellow"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 7,
		"points": 6,
		"level": 1,
		"rulesType": "FEROCITY-4",
		"flavorText": "This lucky bug looks like it's wearing a space suit.",
		"image": null,
	},
	"M66": {
		"name": "Madagascar Serpent Eagle",
		"pack": "Madagascar",
		"number": 66,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Eutriochis astur",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange", "red"],
			"right": ["red", "orange"]
			"top": [],
			"bottom": ["orange", "red"],
		},
		"energy": 5,
		"points": 8,
		"level": 3,
		"rulesType": "TURFSPECIES-REPTILE-8",
		"flavorText": "Recently rediscovered species - once thought to be extinct...",
		"image": null,
	},
	"M67": {
		"name": "Madagascar Leaf-nosed Snake",
		"pack": "Madagascar",
		"number": 67,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Langaha madagascariensis",
		"rarity": "Common",
		"borders": {
			"left": ["orange", "red"],
			"right": []
			"top": ["orange", "red"],
			"bottom": ["orange", "red"],
		},
		"energy": 6,
		"points": 11,
		"level": 3,
		"rulesType": "",
		"flavorText": "Is that branch mooooooving? It's a snake ... make that two snakes! The male has a \"stick\" nose and the female a \"leaf\".",
		"image": null,
	},
	"M68": {
		"name": "Olive Ridley Sea Turtle",
		"pack": "Madagascar",
		"number": 68,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Lepidochelys olivacea",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange", "red"],
			"right": []
			"top": ["orange", "red"],
			"bottom": ["orange", "red"],
		},
		"energy": 10,
		"points": 7,
		"level": 3,
		"rulesType": "SUNRISE-MIGRATE-2",
		"flavorText": "",
		"image": null,
	},
	"M69": {
		"name": "Madagascan Tree Boa",
		"pack": "Madagascar",
		"number": 69,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Sanzinia madagascariensis",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": ["orange", "red"]
			"top": [],
			"bottom": ["orange", "red"],
		},
		"energy": 10,
		"points": 6,
		"level": 3,
		"rulesType": "MORPH-2",
		"flavorText": "Sssssssssnakes are sssssssacred.",
		"image": null,
	},
	"M70": {
		"name": "Sickle-billed Vanga",
		"pack": "Madagascar",
		"number": 70,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Falculea palliata",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["red", "orange"],
		},
		"energy": 8,
		"points": 8,
		"level": 3,
		"rulesType": "SUNRISE-WARNING",
		"flavorText": "",
		"image": null,
	},
	"M71": {
		"name": "Madagascar Crested Ibis",
		"pack": "Madagascar",
		"number": 71,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Lophotibis cristata",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["orange"]
			"top": ["red", "orange"],
			"bottom": ["red"],
		},
		"energy": 11,
		"points": 10,
		"level": 3,
		"rulesType": "",
		"flavorText": "Large terrestrial bird with chestnut coloring, green crest, large curved bill and white wings. SQUAWK!",
		"image": null,
	},
	"M72": {
		"name": "Scorpion",
		"pack": "Madagascar",
		"number": 72,
		"cardType": "Species",
		"speciesType": "Arachnid",
		"speciesName": "Grosphus palpator",
		"rarity": "Common",
		"borders": {
			"left": ["orange", "red"],
			"right": ["orange", "red"]
			"top": [],
			"bottom": ["orange", "red"],
		},
		"energy": 13,
		"points": 5,
		"level": 3,
		"rulesType": "TURFDIAGONAL",
		"flavorText": "Beware the scorpion's sting.",
		"image": null,
	},
	"M73": {
		"name": "Madagascar Sideneck Turtle",
		"pack": "Madagascar",
		"number": 73,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Erymnochelys madagascariensis",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange"],
			"right": ["red"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 12,
		"points": 9,
		"level": 3,
		"rulesType": "SUNRISE-MIGRATE-2",
		"flavorText": "",
		"image": null,
	},
	"M74": {
		"name": "Madagascar Ground Boa",
		"pack": "Madagascar",
		"number": 74,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Acrantophis madagascariensis",
		"rarity": "Rare",
		"borders": {
			"left": ["red"],
			"right": []
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 9,
		"points": 11,
		"level": 3,
		"rulesType": "",
		"flavorText": "Ssssssssss ... I have room for ... ssssssssss ... one more.",
		"image": null,
	},
	"M75": {
		"name": "Madagascar Heron",
		"pack": "Madagascar",
		"number": 75,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Ardea humbloti",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["red"],
		},
		"energy": 10,
		"points": 8,
		"level": 3,
		"rulesType": "DEFEND-4-4",
		"flavorText": "This wetland wonder likes fresh fish.",
		"image": null,
	},
	"M76": {
		"name": "Striped Civet",
		"pack": "Madagascar",
		"number": 76,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Fossa fossana",
		"rarity": "Rare",
		"borders": {
			"left": ["orange"],
			"right": ["orange", "red"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 12,
		"points": 9,
		"level": 3,
		"rulesType": "",
		"flavorText": "Fat tails! Striped Civets store fat reserves in their tails as an energy source for winter.",
		"image": null,
	},
	"M77": {
		"name": "Madagascar Red Owl",
		"pack": "Madagascar",
		"number": 77,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Tyto soumagnei",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["orange", "red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 13,
		"points": 11,
		"level": 3,
		"rulesType": "",
		"flavorText": "One of the 50 rarest birds in the world. Voice: Hissing call.",
		"image": null,
	},
	"M78": {
		"name": "Loggerhead Sea Turtle",
		"pack": "Madagascar",
		"number": 78,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Caretta caretta",
		"rarity": "Rare",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["red"],
			"bottom": ["orange", "red"],
		},
		"energy": 12,
		"points": 8,
		"level": 3,
		"rulesType": "SUNRISE-MIGRATE-2",
		"flavorText": "",
		"image": null,
	},
	"M79": {
		"name": "Leatherback Sea Turtle",
		"pack": "Madagascar",
		"number": 79,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Dermochelys coiacea",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 12,
		"points": 10,
		"level": 3,
		"rulesType": "NEST-4",
		"flavorText": "Found from tropical to sub-polar oceans.",
		"image": null,
	},
	"M80": {
		"name": "Panther Chameleon",
		"pack": "Madagascar",
		"number": 80,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Furcifer pardalis",
		"rarity": "Rare",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["red", "orange"],
			"bottom": ["red"],
		},
		"energy": 10,
		"points": 9,
		"level": 3,
		"rulesType": "SUNRISE-WARNING",
		"flavorText": "",
		"image": null,
	},
	"M81": {
		"name": "Thorn Spider",
		"pack": "Madagascar",
		"number": 81,
		"cardType": "Species",
		"speciesType": "Arachnid",
		"speciesName": "Gasteracantha versicolor",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "orange"],
			"right": []
			"top": ["orange", "yellow"],
			"bottom": ["yellow", "orange"],
		},
		"energy": 10,
		"points": 5,
		"level": 2,
		"rulesType": "FEROCITY-2",
		"flavorText": "Fake eyes fake out!",
		"image": null,
	},
	"M82": {
		"name": "Oustalet's Chameleon",
		"pack": "Madagascar",
		"number": 82,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Furcifer oustaleti",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"]
			"top": [],
			"bottom": ["yellow", "orange"],
		},
		"energy": 10,
		"points": 5,
		"level": 2,
		"rulesType": "NEST-3",
		"flavorText": "\"Go about life the way a chameleon walk; face what is in front and look back at what is behind.\" - Malagasy Proverb",
		"image": null,
	},
	"M83": {
		"name": "Van Dam's Vagna",
		"pack": "Madagascar",
		"number": 83,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Xenopirostris damii",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"]
			"top": ["yellow", "orange"],
			"bottom": [],
		},
		"energy": 10,
		"points": 6,
		"level": 2,
		"rulesType": "SUNRISE-MIGRATE-2",
		"flavorText": "Calls TSEEANG very loudly.",
		"image": null,
	},
	"M84": {
		"name": "Greater Hedgehog Tenrec",
		"pack": "Madagascar",
		"number": 84,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Setifer setosus",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "orange"],
			"right": []
			"top": ["yellow", "orange"],
			"bottom": ["yellow", "orange"],
		},
		"energy": 11,
		"points": 6,
		"level": 2,
		"rulesType": "",
		"flavorText": "Shake, rattle and roll! Masters of stridulation (the vibrating of spines to produce a rasping sound) this is one animal that you don't want to upset!",
		"image": null,
	},
	"M85": {
		"name": "Aye-aye",
		"pack": "Madagascar",
		"number": 85,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Daubentonia madagascariensis",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange"],
			"right": ["yellow", "orange"]
			"top": ["yellow"],
			"bottom": ["yellow", "orange"],
		},
		"energy": 10,
		"points": 7,
		"level": 2,
		"rulesType": "TURFSPECIES-INSECT-8",
		"flavorText": "This nocturnal lemur has continuously-growing incisor teeth and EXTRA-long middle fingers (great for digging grubs).",
		"image": null,
	},
	"M86": {
		"name": "Giant Jumping Rat",
		"pack": "Madagascar",
		"number": 86,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Hypogeomys antimena",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["yellow", "blue"],
			"bottom": ["blue"],
		},
		"energy": 6,
		"points": 6,
		"level": 2,
		"rulesType": "MORPH-3",
		"flavorText": "Is that a rat or a kangaroo???",
		"image": null,
	},
	"M87": {
		"name": "Brown Mouse Lemur",
		"pack": "Madagascar",
		"number": 87,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Microcebus griseorufus",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["blue"],
			"bottom": ["yellow"],
		},
		"energy": 5,
		"points": 4,
		"level": 2,
		"rulesType": "TURFMOMENTUM",
		"flavorText": "The smallest primate on the planet is as small as a walnut!",
		"image": null,
	},
	"M88": {
		"name": "Madagascar Flying Fox",
		"pack": "Madagascar",
		"number": 88,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Pteropus rufus",
		"rarity": "Rare",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["yellow"]
			"top": ["yellow"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 12,
		"points": 4,
		"level": 2,
		"rulesType": "TURFDIAGONAL",
		"flavorText": "Quiet shadows come gliding in. These nocturnal flyers are seed spreaders.",
		"image": null,
	},
	"M90": {
		"name": "Madagascar Ground Gecko",
		"pack": "Madagascar",
		"number": 90,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Paroedura pictus",
		"rarity": "Common",
		"borders": {
			"left": ["yellow"],
			"right": ["orange"]
			"top": ["yellow"],
			"bottom": ["yellow", "orange"],
		},
		"energy": 10,
		"points": 5,
		"level": 2,
		"rulesType": "MORPH-2",
		"flavorText": "Well grounded - Pictus does not climb walls.",
		"image": null,
	},
	"M91": {
		"name": "Running Coua",
		"pack": "Madagascar",
		"number": 91,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Coua cursor",
		"rarity": "Common",
		"borders": {
			"left": ["orange"],
			"right": ["orange", "yellow"]
			"top": ["yellow"],
			"bottom": ["yellow"],
		},
		"energy": 10,
		"points": 5,
		"level": 2,
		"rulesType": "SUNRISE-MIGRATE-2",
		"flavorText": "Vivid blue eye-patch.",
		"image": null,
	},
	"M92": {
		"name": "Coppery Day Gecko",
		"pack": "Madagascar",
		"number": 92,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Phelsuma madagascariensis",
		"rarity": "Common",
		"borders": {
			"left": ["yellow"],
			"right": ["blue"]
			"top": ["yellow"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 9,
		"points": 6,
		"level": 2,
		"rulesType": "",
		"flavorText": "To hear a gecko bark is good luck (and good hearing)!",
		"image": null,
	},
	"M93": {
		"name": "White-breasted Mesite",
		"pack": "Madagascar",
		"number": 93,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Mesitornis variegata",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["orange", "yellow"],
			"bottom": ["yellow"],
		},
		"energy": 7,
		"points": 8,
		"level": 2,
		"rulesType": "DEFEND-2-4",
		"flavorText": "Walks slowly, flicking over leaves in search of snacks.",
		"image": null,
	},
	"M94": {
		"name": "Ring-tailed Lemur",
		"pack": "Madagascar",
		"number": 94,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Lemur catta",
		"rarity": "Rare",
		"borders": {
			"left": ["blue"],
			"right": ["yellow"]
			"top": ["yellow", "blue"],
			"bottom": ["yellow"],
		},
		"energy": 8,
		"points": 5,
		"level": 2,
		"rulesType": "DEFEND-1-4",
		"flavorText": "Ambassador. Social, keen sense of smell, and a fabulous ring tail.",
		"image": null,
	},
	"M95": {
		"name": "Madagascar Teal",
		"pack": "Madagascar",
		"number": 95,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Anas bernieri",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow", "blue"]
			"top": ["orange"],
			"bottom": ["yellow"],
		},
		"energy": 5,
		"points": 2,
		"level": 2,
		"rulesType": "DEFEND-3-5",
		"flavorText": "Small dabbling duck. The rarest duck in the world.",
		"image": null,
	},
	"M96": {
		"name": "Compass",
		"pack": "Madagascar",
		"number": 96,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1],
		"rulesType": "",
		"flavorText": "The compass enables field agents to move like magic. -XM",
		"image": null,
	},
	"M97": {
		"name": "Three Totems",
		"pack": "Madagascar",
		"number": 97,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,1],
		"rulesType": "",
		"flavorText": "Local culture is almost as endangered as the animals. Three is considered a lucky number - whose luck is it? - ZX",
		"image": null,
	},
	"M98": {
		"name": "Field Binoculars",
		"pack": "Madagascar",
		"number": 98,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,1,2],
		"rulesType": "",
		"flavorText": "My Xeko binocs seem to have some new features... can't wait to test these tomorrow. - XFA",
		"image": null,
	},
	"M99": {
		"name": "Eco-map",
		"pack": "Madagascar",
		"number": 99,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,4],
		"rulesType": "",
		"flavorText": "The lemurs on my eco-map are moving ... wonder what's up? - XFA",
		"image": null,
	},
	"M100": {
		"name": "Field Kit",
		"pack": "Madagascar",
		"number": 100,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,1,3],
		"rulesType": "",
		"flavorText": "Spare socks came in handy after a day tracking lemurs in the rainforest. - XFA",
		"image": null,
	},
	"M101": {
		"name": "Ambassador's Pass",
		"pack": "Madagascar",
		"number": 101,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [2,2],
		"rulesType": "",
		"flavorText": "Send thank you to King Andrianampoinimerinandriansimitoviaminandriampanjaka. - ZA",
		"image": null,
	},
	"M102": {
		"name": "Forest Fire",
		"pack": "Madagascar",
		"number": 102,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,2],
		"rulesType": "",
		"flavorText": "A fire wiped out a good deal of habitat in the Northeast. Wonder what caused it? - XFA",
		"image": null,
	},
	"M103": {
		"name": "16 Palm Nuts",
		"pack": "Madagascar",
		"number": 103,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,2,3],
		"rulesType": "",
		"flavorText": "An ombiasy read my palm nuts - said Dozers were afoot. -XFA",
		"image": null,
	},
	"M104": {
		"name": "Code: LAMINA",
		"pack": "Madagascar",
		"number": 104,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1],
		"rulesType": "",
		"flavorText": "Encoded message from XHQ.",
		"image": null,
	},
	"M105": {
		"name": "Peace Offering",
		"pack": "Madagascar",
		"number": 105,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [0,1,2],
		"rulesType": "",
		"flavorText": "\"Fandriampahalemana\" means \"peace\" in Malagasy. - ZX",
		"image": null,
	},
	"M106": {
		"name": "Elemental: Air",
		"pack": "Madagascar",
		"number": 106,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [3],
		"rulesType": "",
		"flavorText": "Elemental at your service!",
		"image": null,
	},
	"M107": {
		"name": "Elemental: Water",
		"pack": "Madagascar",
		"number": 107,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [3,3],
		"rulesType": "",
		"flavorText": "Elemental at your service!",
		"image": null,
	},
	"M108": {
		"name": "Elemental: Earth",
		"pack": "Madagascar",
		"number": 108,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [3,3],
		"rulesType": "",
		"flavorText": "Elemental at your service!",
		"image": null,
	},
	"M109": {
		"name": "New Reserve",
		"pack": "Madagascar",
		"number": 109,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [3,3,3],
		"rulesType": "",
		"flavorText": "President declared new reserve - can't wait to tell XHQ! - XFA",
		"image": null,
	},
	"M110": {
		"name": "Critical Levels",
		"pack": "Madagascar",
		"number": 110,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [2,3,3],
		"rulesType": "",
		"flavorText": "Urgent: Warning sign spotted - habitat too weak. Need more help. - XFA",
		"image": null,
	},
	"M111": {
		"name": "Smuggler Captured",
		"pack": "Madagascar",
		"number": 111,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [4,4],
		"rulesType": "",
		"flavorText": "",
		"image": null,
	},
	"M112": {
		"name": "Ancient Text",
		"pack": "Madagascar",
		"number": 112,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,1,4],
		"rulesType": "",
		"flavorText": "Sorabe found by XFA - what an incredible knowledge trove! - ZA",
		"image": null,
	},
	"M113": {
		"name": "Vintana: Destiny",
		"pack": "Madagascar",
		"number": 113,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,2,3,4],
		"rulesType": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": ,
		"rulesType": "",
		"flavorText": "",
		"image": null,
	},
	"M114": {
		"name": "Dozer Mischief",
		"pack": "Madagascar",
		"number": 114,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [3,4],
		"rulesType": "",
		"flavorText": "Dozers strike again! - XFA",
		"image": null,
	},
	"M115": {
		"name": "Elemental: Fire",
		"pack": "Madagascar",
		"number": 115,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [2,3,4],
		"rulesType": "",
		"flavorText": "Elemental at your service!",
		"image": null,
	},
	"M116": {
		"name": "Madagascar - Hotspot",
		"pack": "Madagascar",
		"number": 116,
		"cardType": "Hotspot",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"top": ["blue"],
			"bottom": ["blue"],
			"left": ["blue"],
			"right": ["blue"]
		},
		"energy": 0,
		"points": 0,
		"level": ,
		"rulesType": "",
		"flavorText": "",
		"image": null,
	}
};