// TODO: find a better way to save rulesType for function restoration
// missing cards: M2 (Lightning Strike), M38 (Golden Frog),
let config_M = {
	"M0": {
		"name": "",
		"pack": "",
		"number": 0,
		"cardType": "",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M1": {
		"name": "Camouflage",
		"pack": "Madagascar",
		"number": 1,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["blue"],
			"top": ["orange", "yellow"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5",
		"rulesText": "+5 Energy",
		"flavorText": "Great defense - animals blend in to hide.",
		"image": null,
	},
	"M2": {
		"name": "Fresh Spring",
		"pack": "Madagascar",
		"number": 2,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["orange", "red", "blue"],
			"top": [],
			"bottom": ["blue", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-4",
		"rulesText": "+4 Energy",
		"flavorText": "A quick drink refreshes.",
		"image": null,
	},
	"M3": {
		"name": "Warning Sign",
		"pack": "Madagascar",
		"number": 3,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange"],
			"right": ["orange", "yellow"],
			"top": ["orange", "yellow"],
			"bottom": ["yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-ENEMYHAND",
		"rulesText": "Add energy equal to the number of cards in opponent's hand.",
		"flavorText": "Birds take flight giving warning that something big is on its way.",
		"image": null,
	},
	"M4": {
		"name": "Vacant Cave",
		"pack": "Madagascar",
		"number": 4,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": [],
			"top": ["red"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-10",
		"rulesText": "+10 Energy",
		"flavorText": "Great place to hide ... hope it's empty!",
		"image": null,
	},
	"M6": {
		"name": "Swarm",
		"pack": "Madagascar",
		"number": 6,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": [],
			"right": ["yellow", "blue"],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "blue"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-TROPHIC1MULT2",
		"rulesText": "Add Energy equal to the number of level 1 species in play times 2.",
		"flavorText": "There's strength in numbers.",
		"image": null,
	},
	"M7": {
		"name": "Disguise",
		"pack": "Madagascar",
		"number": 7,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["orange"],
			"top": ["orange", "yellow"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-2-5",
		"rulesText": "+3 Energy. Add an additional +5 Energy if played on a level 2 species.",
		"flavorText": "To be invisible, blend in.",
		"image": null,
	},	
	"M8": {
		"name": "Armour",
		"pack": "Madagascar",
		"number": 8,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": [],
			"top": ["orange"],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-3-5",
		"rulesText": "+3 Energy. Add an additional +5 Energy if played on a level 3 species.",
		"flavorText": "Crusty shell protects so well!",
		"image": null,
	},	
	"M9": {
		"name": "Heavy Storm",
		"pack": "Madagascar",
		"number": 9,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": [],
			"right": ["orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFTIE",
		"rulesText": "This Turf War end in a tie.",
		"flavorText": "All creatures, big and small, take cover in heavy weather.",
		"image": null,
	},	
	"M10": {
		"name": "Stridulation",
		"pack": "Madagascar",
		"number": 10,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "red"],
			"right": ["red", "orange"],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-3-REUSECARD",
		"rulesText": "+3 Energy. Shuffle the card back into your Draw Pile when played.",
		"flavorText": "The vibrating of spines to make a resping sound scares some predators away.",
		"image": null,
	},	
	"M11": {
		"name": "Food Stash",
		"pack": "Madagascar",
		"number": 11,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": ["red", "orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-7-REUSECARD",
		"rulesText": "+7 Energy. Shuffle this card back into your Draw Pile when played.",
		"flavorText": "Quick snack gives extra energy.",
		"image": null,
	},	
	"M12": {
		"name": "Toxic",
		"pack": "Madagascar",
		"number": 12,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["yellow"],
			"right": [],
			"top": ["red", "yellow"],
			"bottom": ["yellow", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-BASEENERGY",
		"rulesText": "Add Energy equal to the base Energy of the Species card.",
		"flavorText": "Some species acquire toxins through their diet, making them poisonous and yucky-tasting. The Mantella baroni snacks on ants.",
		"image": null,
	},	
	"M13": {
		"name": "Rain",
		"pack": "Madagascar",
		"number": 13,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": [],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-REUSECARD",
		"rulesText": "+5 Energy. Shuffle this card back into your Draw Pile when played.",
		"flavorText": "Tsy misy ala, tsy misy rano, tsy misy vary!",
		"image": null,
	},	
	"M14": {
		"name": "Hiding Spot",
		"pack": "Madagascar",
		"number": 14,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "orange"],
			"right": ["orange", "blue"],
			"top": ["orange", "yellow"],
			"bottom": ["blue", "yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-3-DRAWCARD-1",
		"rulesText": "+3 Energy. Draw a card.",
		"flavorText": "Lie low and keep quiet until trouble passes by...",
		"image": null,
	},	
	"M15": {
		"name": "Sticky Web Trap",
		"pack": "Madagascar",
		"number": 15,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["orange", "blue"],
			"top": ["yellow", "orange", "blue"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFENEMYUSELESSBOOSTS",
		"rulesText": "During this Turf War, all Boost cards played by opponent increase Energy by 0.",
		"flavorText": "Gumbed up in a spider's sticky web.",
		"image": null,
	},	
	"M16": {
		"name": "Up a Tree",
		"pack": "Madagascar",
		"number": 16,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["red", "yellow"],
			"top": ["orange", "red", "yellow"],
			"bottom": ["yellow", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-NOTFIRSTBOOST-5",
		"rulesText": "+5 Energy. If this is not your first Boost card in this Turf War, add an additional +5 Energy.",
		"flavorText": "Out of harm's reach?",
		"image": null,
	},	
	"M17": {
		"name": "Full Moon",
		"pack": "Madagascar",
		"number": 17,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"],
			"top": ["yellow", "orange"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-6",
		"rulesText": "+6 Energy",
		"flavorText": "Moon light, shine bright. Light the earth for the hunt tonight.",
		"image": null,
	},	
	"M18": {
		"name": "Fangs!",
		"pack": "Madagascar",
		"number": 18,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"],
			"top": ["yellow"],
			"bottom": ["yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-2-3",
		"rulesText": "+5 Energy. Add an additional +3 Energy if played on a level 2 species.",
		"flavorText": "Sharp teeth --- big bite! Fangs give Turf War advantage.",
		"image": null,
	},	
	"M19": {
		"name": "Brute Force",
		"pack": "Madagascar",
		"number": 19,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["orange"],
			"right": ["orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-3-3",
		"rulesText": "+5 Energy. Add an additional +3 Energy if played on a level 3 species.",
		"flavorText": "It helps to be big and strong.",
		"image": null,
	},	
	"M20": {
		"name": "Ruckuss!",
		"pack": "Madagascar",
		"number": 20,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "red"],
			"right": ["orange", "yellow"],
			"top": ["orange", "blue"],
			"bottom": ["yellow", "red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-4",
		"rulesText": "+4 Energy",
		"flavorText": "Make crazy noise to win the day.",
		"image": null,
	},	
	"M21": {
		"name": "Symbiosis",
		"pack": "Madagascar",
		"number": 21,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["blue"],
			"right": ["orange", "yellow"],
			"top": ["blue"],
			"bottom": ["orange", "yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFADDENEMYECO",
		"rulesText": "Add Energy equal to the Eco-points of the other species in the Turf War.",
		"flavorText": "Wild collaboration. These clever frogs have a wet home and ready bug supply thanks to the pitcher plant.",
		"image": null,
	},	
	"M22": {
		"name": "Healing Plant",
		"pack": "Madagascar",
		"number": 22,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["blue"],
			"right": ["blue"],
			"top": ["blue"],
			"bottom": ["blue"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-1-3",
		"rulesText": "+5 Energy. Add an additional +3 Energy if played on a level 1 species.",
		"flavorText": "Rosy periwinkle, found only in Madagascar, is considered a miracle plant.",
		"image": null,
	},	
	"M23": {
		"name": "Nocturnal Instinct",
		"pack": "Madagascar",
		"number": 23,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["red"],
			"top": ["red"],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-7-ADDTROPHIC-4-5",
		"rulesText": "+7 Energy. Add an additional +5 Energy if played on a level 4 species",
		"flavorText": "Looking for a midnight snack!",
		"image": null,
	},	
	"M24": {
		"name": "Super Smell",
		"pack": "Madagascar",
		"number": 24,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": [],
			"right": ["red"],
			"top": [],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-10",
		"rulesText": "+10 Energy",
		"flavorText": "Sniff. Sniff! What smells? Oh, it's my tail!",
		"image": null,
	},	
	"M25": {
		"name": "Super Speed",
		"pack": "Madagascar",
		"number": 25,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["purple"],
			"right": ["purple"],
			"top": ["purple"],
			"bottom": ["purple"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-15",
		"rulesText": "+15 Energy",
		"flavorText": "Go fast to catch your prey or get away!",
		"image": null,
	},
	"M26": {
		"name": "Golden Bamboo Lemur",
		"pack": "Madagascar",
		"number": 26,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Hapalemur aureus",
		"rarity": "Vanishing",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 12,
		"points": 10,
		"level": 4,
		"rulesType": "TURFNOBOOST",
		"rulesText": "Boost cards may not be played in Turf Wars involving this card.",
		"flavorText": "One of the world's most endangered. GBL eats daily - 500g of bamboo containing 12 times the amount of cyanide lethal to most animals.",
		"image": null,
	},
	"M27": {
		"name": "Hawk Moth",
		"pack": "Madagascar",
		"number": 27,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Xanthopan morganii praedicta",
		"rarity": "Common",
		"borders": {
			"left": [],
			"right": ["red"]
			"top": [],
			"bottom": ["red"],
		},
		"energy": 13,
		"points": 13,
		"level": 4,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Super-fast flyers and symbiotic with comet orchid. Darwin predicted their existence before they were known.",
		"image": null,
	},
	"M28": {
		"name": "Fossa",
		"pack": "Madagascar",
		"number": 28,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Cryptoprocta ferox",
		"rarity": "Endangered",
		"borders": {
			"left": ["purple"],
			"right": []
			"top": ["purple"],
			"bottom": ["purple"],
		},
		"energy": 14,
		"points": 11,
		"level": 4,
		"rulesType": "FEROCITY-6",
		"rulesText": "Ferocity 6: This species gets +6 Energy when it is the invading species.",
		"flavorText": "One of the world's weirdest - and Madagascar's most ferocious - predators. Said to have a nose like a dog's, teeth like a leopard's and whiskers like an otter's.",
		"image": null,
	},
	"M29": {
		"name": "Hawksbill Sea Turtle",
		"pack": "Madagascar",
		"number": 29,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Eretmochelys imbricata",
		"rarity": "Vanishing",
		"borders": {
			"left": [],
			"right": ["purple", "red"]
			"top": ["purple", "red"],
			"bottom": [],
		},
		"energy": 13,
		"points": 9,
		"level": 4,
		"rulesType": "MORPH-4",
		"rulesText": "Morph 4: You may draw up to 4 cards at the beginning of any Turf War involving this species.",
		"flavorText": "This ocean swimmer loves the taste of sea sponges. Mind the beak!",
		"image": null,
	},
	"M30": {
		"name": "Madagascar Fish Eagle",
		"pack": "Madagascar",
		"number": 30,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Haliaeetus vociferoides",
		"rarity": "Vanishing",
		"borders": {
			"left": ["red", "purple"],
			"right": ["purple", "red"]
			"top": [],
			"bottom": ["red", "purple"],
		},
		"energy": 14,
		"points": 12,
		"level": 4,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Close relative of the bald eagle - one of the most endangered raptors in the world. Loud, measured call: Wha ... wah ... wah ...",
		"image": null,
	},
	"M31": {
		"name": "Golden Crowned Lemur",
		"pack": "Madagascar",
		"number": 31,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Propithecus tattersalli",
		"rarity": "Vanishing",
		"borders": {
			"left": ["red", "purple"],
			"right": []
			"top": ["red", "purple"],
			"bottom": ["red", "purple"],
		},
		"energy": 9,
		"points": 15,
		"level": 4,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "One of the most endangered lemurs and fady to harm. Grooms its (and friends') fur with six lower teeth that stick out to form a funky comb.",
		"image": null,
	},
	"M32": {
		"name": "Ploughshare Tortoise",
		"pack": "Madagascar",
		"number": 32,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Geochelone yniphora",
		"rarity": "Endangered",
		"borders": {
			"left": ["red", "purple"],
			"right": ["red", "purple"]
			"top": ["red", "purple"],
			"bottom": [],
		},
		"energy": 10,
		"points": 10,
		"level": 4,
		"rulesType": "NEST-6",
		"rulesText": "Nest 6: This species gets +6 Energy when it is the defending species.",
		"flavorText": "In wrestling matches to win a mate, these turtles use their \"plow\" to flip over opponents.",
		"image": null,
	},
	"M33": {
		"name": "Tomato Frog",
		"pack": "Madagascar",
		"number": 33,
		"cardType": "Species",
		"speciesType": "Amphibian",
		"speciesName": "Dyscophus antongili",
		"rarity": "",
		"borders": {
			"left": [],
			"right": ["red", "purple"]
			"top": ["red", "purple"],
			"bottom": ["red", "purple"],
		},
		"energy": 13,
		"points": 6,
		"level": 4,
		"rulesType": "DEFEND-3-4",
		"rulesText": "This species gets +4 Energy when invaded by a level 3 species.",
		"flavorText": " Red like a ripe tomato. As a defense, it secretes a toxic ooze.",
		"image": null,
	},
	"M34": {
		"name": "Giant Leaf-tailed Gecko",
		"pack": "Madagascar",
		"number": 34,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Uroplatus fimbriatus",
		"rarity": "Common",
		"borders": {
			"left": ["red", "purple"],
			"right": []
			"top": ["red", "purple"],
			"bottom": [],
		},
		"energy": 11,
		"points": 14,
		"level": 4,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Gecko with perfect tree camouflage. Bark-like skin, large eyes, no eye lids, a flip-top head and leaf-like tail.",
		"image": null,
	},
	"M35": {
		"name": "Nile Crocodile",
		"pack": "Madagascar",
		"number": 35,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Crocodylus niloticus",
		"rarity": "Common",
		"borders": {
			"left": [],
			"right": ["red", "purple"]
			"top": [],
			"bottom": ["red", "purple"],
		},
		"energy": 15,
		"points": 8,
		"level": 4,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "One tough and hungry crock - where did that bird go? (Burp!)",
		"image": null,
	},
	"M36": {
		"name": "Giant-striped Mongoose",
		"pack": "Madagascar",
		"number": 36,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Galidictis grandidieri",
		"rarity": "Endangered",
		"borders": {
			"left": ["red", "purple"],
			"right": []
			"top": ["red", "purple"],
			"bottom": ["red", "purple"],
		},
		"energy": 10,
		"points": 9,
		"level": 4,
		"rulesType": "TURFSPECIES-REPTILE-4",
		"rulesText": "This species gets +4 Energy when involved in a Turf War with a Reptile species.",
		"flavorText": "Nocturnal and crepuscular - active at night and at twilight.",
		"image": null,
	},
	"M37": {
		"name": "Malagasy Ring-tailed Mongoose",
		"pack": "Madagascar",
		"number": 37,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Galidia elegans",
		"rarity": "Rare",
		"borders": {
			"left": [],
			"right": ["red", "purple"]
			"top": [],
			"bottom": ["red", "purple"],
		},
		"energy": 10,
		"points": 11,
		"level": 4,
		"rulesType": "TURFSPECIES-REPTILE-4",
		"rulesText": "This species gets +4 Energy when involved in a Turf War with a Reptile species.",
		"flavorText": "Diurnal and gregarious - active and playful during the day.",
		"image": null,
	},
	"M39": {
		"name": "Commerson's Leaf-nosed Bat",
		"pack": "Madagascar",
		"number": 39,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Hipposideros commersoni",
		"rarity": "Common",
		"borders": {
			"left": ["purple"],
			"right": ["red"]
			"top": ["purple"],
			"bottom": ["purple"],
		},
		"energy": 11,
		"points": 12,
		"level": 4,
		"rulesType": "TURFDIAGONAL",
		"rulesText": "This species may start a Turf War with a species diagonally.",
		"flavorText": "Holy bat-nose! With a wingspan of nearly 2 feet, it's one of the largest insectivors in Africa.",
		"image": null,
	},
	"M40": {
		"name": "Hairy-eared Dwarf Lemur",
		"pack": "Madagascar",
		"number": 40,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Allocebus trichotis",
		"rarity": "Vanishing",
		"borders": {
			"left": ["purple"],
			"right": ["purple"]
			"top": ["purple"],
			"bottom": ["purple"],
		},
		"energy": 7,
		"points": 17,
		"level": 4,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "One of the rarest, smallest - and cutest - primates on the planet, once thought extinct, this lemur was \"rediscovered\" with the help of a Malagasy local.",
		"image": null,
	},
	"M41": {
		"name": "Alluaudia Spiny Plant",
		"pack": "Madagascar",
		"number": 41,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Alluaudia montagnacii",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["yellow"],
			"bottom": ["yellow"],
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "PLANT-TROPHICCOUNT3",
		"rulesText": "This card cannot be involved in a Turf War. Eco-points = the number of level 3 species.",
		"flavorText": "A prickly perch.",
		"image": null,
	},
	"M42": {
		"name": "Comet Orchid",
		"pack": "Madagascar",
		"number": 42,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Angraecum sesquipedale",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "PLANT-HAWKMOTH",
		"rulesText": "This card cannot be involved in a Turf War. When you play this card, you may immediately play a Hawk Moth from your hand. A Hawk Moth card played in this way must be attached to this card.",
		"flavorText": "",
		"image": null,
	},
	"M43": {
		"name": "Dutchman's Pipe",
		"pack": "Madagascar",
		"number": 43,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Aristolochia",
		"rarity": "Common",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "PLANT-TROPHICCOUNT2",
		"rulesText": "This card cannot be involved in a Turf War. Eco-points = the number of level 2 species.",
		"flavorText": "The flowers of most Aristolochia emit a powerful stench - smells like rotting meat. Pee-eew!",
		"image": null,
	},
	"M44": {
		"name": "Carnivorous Pitcher Plant",
		"pack": "Madagascar",
		"number": 44,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Nepenthes madagascariensis",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"]
			"top": ["yellow", "orange"],
			"bottom": ["yellow", "orange"],
		},
		"energy": 0,
		"points": 0,
		"level": [0,2],
		"rulesType": "PLANT-PITCHER", 
		"rulesText": "Eco-points and Energy = the number of all Insect species.",
		"flavorText": "The pretty plant is deadly to bugs. Digests insects for a meal.",
		"image": null,
	},
	"M45": {
		"name": "Voantany",
		"pack": "Madagascar",
		"number": 45,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Hydnora esculenta",
		"rarity": "Rare",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 0,
		"points": 3,
		"level": 0,
		"rulesType": "PLANT-SUNRISEDRAW",
		"rulesText": "This card cannot be involved in a Turf War. SUNRISE: At the beginning of your turn, you may draw an additional card.",
		"flavorText": "Lemurs' favorite. Extremely rare and known as \"fruit of the earth.\"",
		"image": null,
	},
	"M46": {
		"name": "Grandidier Baobab",
		"pack": "Madagascar",
		"number": 46,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Adansonia grandidieri",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["yellow"],
			"bottom": ["yellow"],
		},
		"energy": 0,
		"points": 3,
		"level": [0,1,4],
		"rulesType": "PLANT",
		"rulesText": "This card cannot be involved in a Turf War.",
		"flavorText": "African tree of life. Sacred.",
		"image": null,
	},
	"M47": {
		"name": "White Lotus",
		"pack": "Madagascar",
		"number": 47,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Nymphaea lotus",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 0,
		"points": 5,
		"level": 0,
		"rulesType": "PLANT-ADJBOOST-1",
		"rulesText": "This card cannot be involved in a Turf War. Your adjacent species gain +1 Energy.",
		"flavorText": "An old and evolutionarily primitive beauty.",
		"image": null,
	},
	"M48": {
		"name": "Tamarind Tree",
		"pack": "Madagascar",
		"number": 48,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Tamarindus indica",
		"rarity": "Common",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"]
			"top": ["yellow"],
			"bottom": ["yellow"],
		},
		"energy": 0,
		"points": 3,
		"level": 0,
		"rulesType": "PLANT-ADJBOOST-3",
		"rulesText": "This card cannot be involved in a Turf War. Your adjacent species gain +3 Energy.",
		"flavorText": "Lemur catta's favorite.",
		"image": null,
	},
	"M49": {
		"name": "Travelers Palm",
		"pack": "Madagascar",
		"number": 49,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Ravenala madagascariensis",
		"rarity": "Common",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 0,
		"points": 4,
		"level": 0,
		"rulesType": "PLANT-ADJBOOST-2",
		"rulesText": "This card cannot be involved in a Turf War. Your adjacent species gain +2 Energy.",
		"flavorText": "A welcome sign.",
		"image": null,
	},
	"M50": {
		"name": "Giant Bamboo",
		"pack": "Madagascar",
		"number": 50,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Cathariostachys madagascariensis",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 0,
		"points": 4,
		"level": 0,
		"rulesType": "PLANT-GIANTBAMBOO",
		"rulesText": "This card cannot be involved in a Turf War. If a Golden Bamboo Lemur is attached to this card, that card gains +5 Energy.",
		"flavorText": "High in protein as well as cyanide.",
		"image": null,
	},
	"M51": {
		"name": "Indri",
		"pack": "Madagascar",
		"number": 51,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Indri indri",
		"rarity": "Endangered",
		"borders": {
			"left": ["blue"],
			"right": ["yellow", "blue"]
			"top": ["blue"],
			"bottom": ["yellow", "blue"],
		},
		"energy": 6,
		"points": 3,
		"level": 1,
		"rulesType": "TURFMOMENTUM",
		"rulesText": "If this species wins a Turf War, you may immediately play a Species card from you hand (playing that card does not start a Turf War).",
		"flavorText": "\"There it is.\"",
		"image": null,
	},
	"M52": {
		"name": "Verreaux's Sifaka",
		"pack": "Madagascar",
		"number": 52,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Propithecus verreauxii",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["blue"]
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "blue"],
		},
		"energy": 9,
		"points": 5,
		"level": 1,
		"rulesType": "TURFINVADETROPHIC-2-3",
		"rulesText": "This species gets +3 Energy when invading a level 2 species.",
		"flavorText": "Great gliders. Capable of making giant jumps through trees - leaps of 30 ft are not uncommon!",
		"image": null,
	},
	"M53": {
		"name": "Woolly Lemur",
		"pack": "Madagascar",
		"number": 53,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Avahi laniger",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["yellow", "blue"]
			"top": [],
			"bottom": ["yellow", "blue"],
		},
		"energy": 8,
		"points": 6,
		"level": 1,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Out at night with eyes so bright.",
		"image": null,
	},
	"M54": {
		"name": "Flat-tailed Tortoise",
		"pack": "Madagascar",
		"number": 54,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Pyxix planicauda",
		"rarity": "Endangered",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["yellow", "blue"]
			"top": ["yellow", "blue"],
			"bottom": [],
		},
		"energy": 7,
		"points": 5,
		"level": 1,
		"rulesType": "TURFINVADETROPHIC-1-5",
		"rulesText": "This species gets +5 Energy when invading a level 1 species.",
		"flavorText": "Known locally as Kapidolo (ghost turtle).",
		"image": null,
	},
	"M55": {
		"name": "Katydid",
		"pack": "Madagascar",
		"number": 55,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Aspidonotus spinosus",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["blue"]
			"top": [],
			"bottom": ["yellow", "blue"],
		},
		"energy": 10,
		"points": 5,
		"level": 1,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "What can a bug do to hide? Make like a tree and leaf!",
		"image": null,
	},
	"M56": {
		"name": "Spider Tortoise",
		"pack": "Madagascar",
		"number": 56,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Pyxis arachnoides",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue"]
			"top": ["yellow", "blue"],
			"bottom": [],
		},
		"energy": 10,
		"points": 5,
		"level": 1,
		"rulesType": "TURFDIAGONAL",
		"rulesText": "Predator: This species may start a Turf War with a species diagonally.",
		"flavorText": "Tortoises are sacred and lucky! It is fady to harm them.",
		"image": null,
	},
	"M57": {
		"name": "Fire Millipede",
		"pack": "Madagascar",
		"number": 57,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Aphistogoniulus",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["blue"]
			"top": [],
			"bottom": ["yellow", "blue"],
		},
		"energy": 9,
		"points": 5,
		"level": 1,
		"rulesType": "TURFFEROCITY-4",
		"rulesText": "Ferocity 4: This species gets +4 Energy when it is the invading species.",
		"flavorText": "Ready ... Aim ... Millipede!",
		"image": null,
	},
	"M58": {
		"name": "Madagascar Hissing Cockroach",
		"pack": "Madagascar",
		"number": 58,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Gromphadorhina portentosa",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "blue"],
			"right": ["yellow", "blue"]
			"top": ["yellow", "blue"],
			"bottom": [],
		},
		"energy": 12,
		"points": 2,
		"level": 1,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Giant cockroaches that hisssssss. Hisssssss. Hissssssssssssssssss.",
		"image": null,
	},
	"M59": {
		"name": "Comet Moth",
		"pack": "Madagascar",
		"number": 59,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Argema mittrei",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 8,
		"points": 5,
		"level": 1,
		"rulesType": "MORPH-1",
		"rulesText": "Morph 1: You may draw 1 card at the beginning of any Turf War involving this species.",
		"flavorText": "These gentle flyers have up to 8-inch wing spans. Tres bizarre: Adult comet moths have no mouths!",
		"image": null,
	},
	"M60": {
		"name": "Giraffe-necked Weevil",
		"pack": "Madagascar",
		"number": 60,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Trachelophorus giraffa",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["blue", "yellow"]
			"top": ["blue", "yellow"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 6,
		"points": 4,
		"level": 1,
		"rulesType": "SUNRISE-MIGRATE-2",
		"rulesText": "SUNRISE: Migrate: Shed 2 cards and move this species to any legal spot on the board (this movement does not start a Turf War).",
		"flavorText": "",
		"image": null,
	},
	"M61": {
		"name": "Clear-winged Butterfly",
		"pack": "Madagascar",
		"number": 61,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Undefined",
		"rarity": "Common",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 8,
		"points": 4,
		"level": 1,
		"rulesType": "TURFINVADETROPHIC-3-8",
		"rulesText": "This species gets +8 Energy when invading a species.",
		"flavorText": "Field agents report in: Help Xeko learn the scientific name for this fancy flyer.",
		"image": null,
	},
	"M62": {
		"name": "Yellow-line Caterpillar",
		"pack": "Madagascar",
		"number": 62,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Lymantriidae",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue", "yellow"]
			"top": ["blue"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 8,
		"points": 6,
		"level": 1,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "This caterpillar eats and eats, munching leaves for a treat.",
		"image": null,
	},
	"M63": {
		"name": "Orange Pill Millipede",
		"pack": "Madagascar",
		"number": 63,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Diplopoda",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["yellow"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 8,
		"points": 6,
		"level": 1,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Two pairs of legs on every ring, makes me so happy I could sing!",
		"image": null,
	},
	"M64": {
		"name": "Radiated Tortoise",
		"pack": "Madagascar",
		"number": 64,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Geochelone radiata",
		"rarity": "Rare",
		"borders": {
			"left": ["blue"],
			"right": ["blue", "yellow"]
			"top": ["blue"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 10,
		"points": 5,
		"level": 1,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "One of the rarest tortoises. Rod's favorite - a true star.",
		"image": null,
	},
	"M65": {
		"name": "Gold Tortoise Beetle",
		"pack": "Madagascar",
		"number": 65,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Cassidinae",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["yellow"]
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 7,
		"points": 6,
		"level": 1,
		"rulesType": "FEROCITY-4",
		"rulesText": "Ferocity 4: This species gets +4 Energy when it is the invading species.",
		"flavorText": "This lucky bug looks like it's wearing a space suit.",
		"image": null,
	},
	"M66": {
		"name": "Madagascar Serpent Eagle",
		"pack": "Madagascar",
		"number": 66,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Eutriochis astur",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange", "red"],
			"right": ["red", "orange"]
			"top": [],
			"bottom": ["orange", "red"],
		},
		"energy": 5,
		"points": 8,
		"level": 3,
		"rulesType": "TURFSPECIES-REPTILE-8",
		"rulesText": "This species gets +8 Energy when involved in a Turf War with a Reptile species.",
		"flavorText": "Recently rediscovered species - once thought to be extinct...",
		"image": null,
	},
	"M67": {
		"name": "Madagascar Leaf-nosed Snake",
		"pack": "Madagascar",
		"number": 67,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Langaha madagascariensis",
		"rarity": "Common",
		"borders": {
			"left": ["orange", "red"],
			"right": []
			"top": ["orange", "red"],
			"bottom": ["orange", "red"],
		},
		"energy": 6,
		"points": 11,
		"level": 3,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Is that branch mooooooving? It's a snake ... make that two snakes! The male has a \"stick\" nose and the female a \"leaf\".",
		"image": null,
	},
	"M68": {
		"name": "Olive Ridley Sea Turtle",
		"pack": "Madagascar",
		"number": 68,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Lepidochelys olivacea",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange", "red"],
			"right": []
			"top": ["orange", "red"],
			"bottom": ["orange", "red"],
		},
		"energy": 10,
		"points": 7,
		"level": 3,
		"rulesType": "SUNRISE-MIGRATE-2",
		"rulesText": "SUNRISE: Migrate: Shed 2 cards and move this species to any legal spot on the board (this movement does not start a Turf War).",
		"flavorText": "",
		"image": null,
	},
	"M69": {
		"name": "Madagascan Tree Boa",
		"pack": "Madagascar",
		"number": 69,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Sanzinia madagascariensis",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": ["orange", "red"]
			"top": [],
			"bottom": ["orange", "red"],
		},
		"energy": 10,
		"points": 6,
		"level": 3,
		"rulesType": "MORPH-2",
		"rulesText": "Morph 2: You may draw up to 2 cards at the beginning of any Turf War involving this species.",
		"flavorText": "Sssssssssnakes are sssssssacred.",
		"image": null,
	},
	"M70": {
		"name": "Sickle-billed Vanga",
		"pack": "Madagascar",
		"number": 70,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Falculea palliata",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["red", "orange"],
		},
		"energy": 8,
		"points": 8,
		"level": 3,
		"rulesType": "SUNRISE-WARNING",
		"rulesText": "SUNRISE: Warning Call: At the beginning of your turn, you may move your adjacent species to another legal spot on the board (this move does not cause a Turf War).",
		"flavorText": "",
		"image": null,
	},
	"M71": {
		"name": "Madagascar Crested Ibis",
		"pack": "Madagascar",
		"number": 71,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Lophotibis cristata",
		"rarity": "Common",
		"borders": {
			"left": ["red"],
			"right": ["orange"]
			"top": ["red", "orange"],
			"bottom": ["red"],
		},
		"energy": 11,
		"points": 10,
		"level": 3,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Large terrestrial bird with chestnut coloring, green crest, large curved bill and white wings. SQUAWK!",
		"image": null,
	},
	"M72": {
		"name": "Scorpion",
		"pack": "Madagascar",
		"number": 72,
		"cardType": "Species",
		"speciesType": "Arachnid",
		"speciesName": "Grosphus palpator",
		"rarity": "Common",
		"borders": {
			"left": ["orange", "red"],
			"right": ["orange", "red"]
			"top": [],
			"bottom": ["orange", "red"],
		},
		"energy": 13,
		"points": 5,
		"level": 3,
		"rulesType": "TURFDIAGONAL",
		"rulesText": "Predator: This species may start a Turf War with a species diagonally.",
		"flavorText": "Beware the scorpion's sting.",
		"image": null,
	},
	"M73": {
		"name": "Madagascar Sideneck Turtle",
		"pack": "Madagascar",
		"number": 73,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Erymnochelys madagascariensis",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange"],
			"right": ["red"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 12,
		"points": 9,
		"level": 3,
		"rulesType": "SUNRISE-MIGRATE-2",
		"rulesText": "SUNRISE: Migrate: Shed 2 cards and move this species to any legal spot on the board (this movement does not start a Turf War).",
		"flavorText": "",
		"image": null,
	},
	"M74": {
		"name": "Madagascar Ground Boa",
		"pack": "Madagascar",
		"number": 74,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Acrantophis madagascariensis",
		"rarity": "Rare",
		"borders": {
			"left": ["red"],
			"right": []
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 9,
		"points": 11,
		"level": 3,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Ssssssssss ... I have room for ... ssssssssss ... one more.",
		"image": null,
	},
	"M75": {
		"name": "Madagascar Heron",
		"pack": "Madagascar",
		"number": 75,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Ardea humbloti",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["orange"]
			"top": ["orange"],
			"bottom": ["red"],
		},
		"energy": 10,
		"points": 8,
		"level": 3,
		"rulesType": "DEFEND-4-4",
		"rulesText": "This species gets +4 Energy when invaded by a level 4 species.",
		"flavorText": "This wetland wonder likes fresh fish.",
		"image": null,
	},
	"M76": {
		"name": "Striped Civet",
		"pack": "Madagascar",
		"number": 76,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Fossa fossana",
		"rarity": "Rare",
		"borders": {
			"left": ["orange"],
			"right": ["orange", "red"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 12,
		"points": 9,
		"level": 3,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "Fat tails! Striped Civets store fat reserves in their tails as an energy source for winter.",
		"image": null,
	},
	"M77": {
		"name": "Madagascar Red Owl",
		"pack": "Madagascar",
		"number": 77,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Tyto soumagnei",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["orange", "red"]
			"top": ["red"],
			"bottom": ["red"],
		},
		"energy": 13,
		"points": 11,
		"level": 3,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "One of the 50 rarest birds in the world. Voice: Hissing call.",
		"image": null,
	},
	"M78": {
		"name": "Loggerhead Sea Turtle",
		"pack": "Madagascar",
		"number": 78,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Caretta caretta",
		"rarity": "Rare",
		"borders": {
			"left": ["orange"],
			"right": ["orange"]
			"top": ["red"],
			"bottom": ["orange", "red"],
		},
		"energy": 12,
		"points": 8,
		"level": 3,
		"rulesType": "SUNRISE-MIGRATE-2",
		"rulesText": "SUNRISE: Migrate: Shed 2 cards and move this species to any legal spot on the board (this movement does not start a Turf War).",
		"flavorText": "",
		"image": null,
	},
	"M79": {
		"name": "Leatherback Sea Turtle",
		"pack": "Madagascar",
		"number": 79,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Dermochelys coiacea",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["red"]
			"top": ["orange"],
			"bottom": ["orange"],
		},
		"energy": 12,
		"points": 10,
		"level": 3,
		"rulesType": "NEST-4",
		"rulesText": "Nest 4: This species gets +4 Energy when it is the defending species.",
		"flavorText": "Found from tropical to sub-polar oceans.",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M": {
		"name": "",
		"pack": "Madagascar",
		"number": ,
		"cardType": "Species",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"left": [],
			"right": []
			"top": [],
			"bottom": [],
		},
		"energy": ,
		"points": ,
		"level": ,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
};