// TODO: find a better way to save rulesType for function restoration
let config_M = {
	"M0": {
		"name": "",
		"pack": "",
		"number": 0,
		"cardType": "",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "",
		"rulesText": "",
		"flavorText": "",
		"image": null,
	},
	"M1": {
		"name": "Camouflage",
		"pack": "Madagascar",
		"number": 1,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["blue"],
			"top": ["orange", "yellow"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5",
		"rulesText": "+5 Energy",
		"flavorText": "Great defense - animals blend in to hide.",
		"image": null,
	},
	"M2": {
		"name": "Fresh Spring",
		"pack": "Madagascar",
		"number": 2,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["orange", "red", "blue"],
			"top": [],
			"bottom": ["blue", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-4",
		"rulesText": "+4 Energy",
		"flavorText": "A quick drink refreshes.",
		"image": null,
	},
	"M3": {
		"name": "Warning Sign",
		"pack": "Madagascar",
		"number": 3,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["orange"],
			"right": ["orange", "yellow"],
			"top": ["orange", "yellow"],
			"bottom": ["yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-ENEMYHAND",
		"rulesText": "Add energy equal to the number of cards in opponent's hand.",
		"flavorText": "Birds take flight giving warning that something big is on its way.",
		"image": null,
	},
	{
		"name": "Vacant Cave",
		"pack": "Madagascar",
		"number": 4,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": [],
			"top": ["red"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-10",
		"rulesText": "+10 Energy",
		"flavorText": "Great place to hide ... hope it's empty!",
		"image": null,
	},
	{
		"name": "Swarm",
		"pack": "Madagascar",
		"number": 6,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": [],
			"right": ["yellow", "blue"],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "blue"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-TROPHIC1MULT2",
		"rulesText": "Add Energy equal to the number of level 1 species in play times 2.",
		"flavorText": "There's strength in numbers.",
		"image": null,
	},
	{
		"name": "Disguise",
		"pack": "Madagascar",
		"number": 7,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["orange"],
			"top": ["orange", "yellow"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-2-5",
		"rulesText": "+3 Energy. Add an additional +5 Energy if played on a level 2 species.",
		"flavorText": "To be invisible, blend in.",
		"image": null,
	},	{
		"name": "Armour",
		"pack": "Madagascar",
		"number": 8,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": [],
			"top": ["orange"],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-3-5",
		"rulesText": "+3 Energy. Add an additional +5 Energy if played on a level 3 species.",
		"flavorText": "Crusty shell protects so well!",
		"image": null,
	},	{
		"name": "Heavy Storm",
		"pack": "Madagascar",
		"number": 9,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": [],
			"right": ["orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFTIE",
		"rulesText": "This Turf War end in a tie.",
		"flavorText": "All creatures, big and small, take cover in heavy weather.",
		"image": null,
	},	{
		"name": "Stridulation",
		"pack": "Madagascar",
		"number": 10,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "red"],
			"right": ["red", "orange"],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-3-REUSECARD",
		"rulesText": "+3 Energy. Shuffle the card back into your Draw Pile when played.",
		"flavorText": "The vibrating of spines to make a resping sound scares some predators away.",
		"image": null,
	},	
	{
		"name": "Food Stash",
		"pack": "Madagascar",
		"number": 11,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": ["red", "orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-7-REUSECARD",
		"rulesText": "+7 Energy. Shuffle this card back into your Draw Pile when played.",
		"flavorText": "Quick snack gives extra energy.",
		"image": null,
	},	
	{
		"name": "Toxic",
		"pack": "Madagascar",
		"number": 12,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["yellow"],
			"right": [],
			"top": ["red", "yellow"],
			"bottom": ["yellow", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-BASEENERGY",
		"rulesText": "Add Energy equal to the base Energy of the Species card.",
		"flavorText": "Some species acquire toxins through their diet, making them poisonous and yucky-tasting. The Mantella baroni snacks on ants.",
		"image": null,
	},	
	{
		"name": "Rain",
		"pack": "Madagascar",
		"number": 13,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["orange", "red"],
			"right": [],
			"top": ["yellow", "blue"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-REUSECARD",
		"rulesText": "+5 Energy. Shuffle this card back into your Draw Pile when played.",
		"flavorText": "Tsy misy ala, tsy misy rano, tsy misy vary!",
		"image": null,
	},	
	{
		"name": "Hiding Spot",
		"pack": "Madagascar",
		"number": 14,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "orange"],
			"right": ["orange", "blue"],
			"top": ["orange", "yellow"],
			"bottom": ["blue", "yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-3-DRAWCARD-1",
		"rulesText": "+3 Energy. Draw a card.",
		"flavorText": "Lie low and keep quiet until trouble passes by...",
		"image": null,
	},	
	{
		"name": "Sticky Web Trap",
		"pack": "Madagascar",
		"number": 15,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["orange", "blue"],
			"top": ["yellow", "orange", "blue"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFENEMYUSELESSBOOSTS",
		"rulesText": "During this Turf War, all Boost cards played by opponent increase Energy by 0.",
		"flavorText": "Gumbed up in a spider's sticky web.",
		"image": null,
	},	
	{
		"name": "Up a Tree",
		"pack": "Madagascar",
		"number": 16,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["red", "yellow"],
			"top": ["orange", "red", "yellow"],
			"bottom": ["yellow", "red", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-NOTFIRSTBOOST-5",
		"rulesText": "+5 Energy. If this is not your first Boost card in this Turf War, add an additional +5 Energy.",
		"flavorText": "Out of harm's reach?",
		"image": null,
	},	
	{
		"name": "Full Moon",
		"pack": "Madagascar",
		"number": 17,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"],
			"top": ["yellow", "orange"],
			"bottom": ["yellow", "orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-6",
		"rulesText": "+6 Energy",
		"flavorText": "Moon light, shine bright. Light the earth for the hunt tonight.",
		"image": null,
	},	{
		"name": "Fangs!",
		"pack": "Madagascar",
		"number": 18,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow"],
			"right": ["yellow"],
			"top": ["yellow"],
			"bottom": ["yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-2-3",
		"rulesText": "+5 Energy. Add an additional +3 Energy if played on a level 2 species.",
		"flavorText": "Sharp teeth --- big bite! Fangs give Turf War advantage.",
		"image": null,
	},	
	{
		"name": "Brute Force",
		"pack": "Madagascar",
		"number": 19,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["orange"],
			"right": ["orange"],
			"top": ["orange"],
			"bottom": ["orange"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-3-3",
		"rulesText": "+5 Energy. Add an additional +3 Energy if played on a level 3 species.",
		"flavorText": "It helps to be big and strong.",
		"image": null,
	},	
	{
		"name": "Ruckuss!",
		"pack": "Madagascar",
		"number": 20,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "red"],
			"right": ["orange", "yellow"],
			"top": ["orange", "blue"],
			"bottom": ["yellow", "red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-4",
		"rulesText": "+4 Energy",
		"flavorText": "Make crazy noise to win the day.",
		"image": null,
	},	
	{
		"name": "Symbiosis",
		"pack": "Madagascar",
		"number": 21,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["blue"],
			"right": ["orange", "yellow"],
			"top": ["blue"],
			"bottom": ["orange", "yellow"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "TURFADDENEMYECO",
		"rulesText": "Add Energy equal to the Eco-points of the other species in the Turf War.",
		"flavorText": "Wild collaboration. These clever frogs have a wet home and ready bug supply thanks to the pitcher plant.",
		"image": null,
	},	
	{
		"name": "Healing Plant",
		"pack": "Madagascar",
		"number": 22,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"left": ["blue"],
			"right": ["blue"],
			"top": ["blue"],
			"bottom": ["blue"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-5-ADDTROPHIC-1-3",
		"rulesText": "+5 Energy. Add an additional +3 Energy if played on a level 1 species.",
		"flavorText": "Rosy periwinkle, found only in Madagascar, is considered a miracle plant.",
		"image": null,
	},	{
		"name": "Nocturnal Instinct",
		"pack": "Madagascar",
		"number": 23,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": ["red"],
			"right": ["red"],
			"top": ["red"],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-7-ADDTROPHIC-4-5",
		"rulesText": "+7 Energy. Add an additional +5 Energy if played on a level 4 species",
		"flavorText": "Looking for a midnight snack!",
		"image": null,
	},	
	{
		"name": "Super Smell",
		"pack": "Madagascar",
		"number": 24,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Endangered",
		"borders": {
			"left": [],
			"right": ["red"],
			"top": [],
			"bottom": ["red"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-10",
		"rulesText": "+10 Energy",
		"flavorText": "Sniff. Sniff! What smells? Oh, it's my tail!",
		"image": null,
	},	
	{
		"name": "Super Speed",
		"pack": "Madagascar",
		"number": 25,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Vanishing",
		"borders": {
			"left": ["purple"],
			"right": ["purple"],
			"top": ["purple"],
			"bottom": ["purple"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": "ADDENERGY-15",
		"rulesText": "+15 Energy",
		"flavorText": "Go fast to catch your prey or get away!",
		"image": null,
	},
};