let deckSample = {
	"SAM1": {
		"name": "Camouflage",
		"pack": "Madagascar",
		"number": 1,
		"cardType": "Boost",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Common",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["blue"],
			"top": ["orange", "yellow"],
			"bottom": []
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesType": {
			addEnergy: 5,
		},
		"rulesText": "+5 Energy",
		"flavorText": "Great defense - animals blend in to hide.",
		"image": null,
	},
	"SAM2": {
		"name": "Fossa",
		"pack": "Madagascar",
		"number": 28,
		"cardType": "Species",
		"speciesType": "Mammal",
		"speciesName": "Cryptoprocta ferox",
		"rarity": "Endangered",
		"borders": {
			"left": ["purple"],
			"right": [],
			"top": ["purple"],
			"bottom": ["purple"],
		},
		"energy": 14,
		"points": 11,
		"level": 4,
		"rulesType": {
			ferocity: 6,
		},
		"rulesText": "Ferocity 6: This species gets +6 Energy when it is the invading species.",
		"flavorText": "One of the world's weirdest - and Madagascar's most ferocious - predators. Said to have a nose like a dog's, teeth like a leopard's and whiskers like an otter's.",
		"image": null,
	},
	"SAM4": {
		"name": "White Lotus",
		"pack": "Madagascar",
		"number": 47,
		"cardType": "Species",
		"speciesType": "Plant",
		"speciesName": "Nymphaea lotus",
		"rarity": "Common",
		"borders": {
			"left": ["blue"],
			"right": ["blue"],
			"top": ["blue"],
			"bottom": ["blue"],
		},
		"energy": 0,
		"points": 5,
		"level": 0,
		"rulesType": {
			peaceful: true,
			benefit: {
				target: "SELF",
				top: 1,
				bottom: 1,
				left: 1,
				right: 1,
			},
		},
		"rulesText": "This card cannot be involved in a Turf War. Your adjacent species gain +1 Energy.",
		"flavorText": "An old and evolutionarily primitive beauty.",
		"image": null,
	},
	"SAM5": {
		"name": "Giraffe-necked Weevil",
		"pack": "Madagascar",
		"number": 60,
		"cardType": "Species",
		"speciesType": "Insect",
		"speciesName": "Trachelophorus giraffa",
		"rarity": "Common",
		"borders": {
			"left": ["blue", "yellow"],
			"right": ["blue", "yellow"],
			"top": ["blue", "yellow"],
			"bottom": ["blue", "yellow"],
		},
		"energy": 6,
		"points": 4,
		"level": 1,
		"rulesType": {
			sunrise: true,

		},
		"rulesText": "SUNRISE: Migrate: Shed 2 cards and move this species to any legal spot on the board (this movement does not start a Turf War).",
		"flavorText": "",
		"image": null,
	},
	"SAM6": {
		"name": "Oustalet's Chameleon",
		"pack": "Madagascar",
		"number": 82,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Furcifer oustaleti",
		"rarity": "Rare",
		"borders": {
			"left": ["yellow", "orange"],
			"right": ["yellow", "orange"],
			"top": [],
			"bottom": ["yellow", "orange"],
		},
		"energy": 10,
		"points": 5,
		"level": 2,
		"rulesText": "Nest 3: This species gets +3 Energy when it is the defending species.",
		"flavorText": "\"Go about life the way a chameleon walk; face what is in front and look back at what is behind.\" - Malagasy Proverb",
		"image": null,
	},
	"SAM7": {
		"name": "Three Totems",
		"pack": "Madagascar",
		"number": 97,
		"cardType": "Xeko",
		"speciesType": "",
		"speciesName": "",
		"rarity": "Rare",
		"borders": {
			"top": [],
			"bottom": [],
			"left": [],
			"right": []
		},
		"energy": 0,
		"points": 0,
		"level": [1,1],
		"rulesText": "Choose a player. That player draws 3 cards.",
		"flavorText": "Local culture is almost as endangered as the animals. Three is considered a lucky number - whose luck is it? - ZX",
		"image": null,
	},
	"SAM8": {
		"name": "Loggerhead Sea Turtle",
		"pack": "Madagascar",
		"number": 78,
		"cardType": "Species",
		"speciesType": "Reptile",
		"speciesName": "Caretta caretta",
		"rarity": "Rare",
		"borders": {
			"left": ["orange"],
			"right": ["orange"],
			"top": ["red"],
			"bottom": ["orange", "red"],
		},
		"energy": 12,
		"points": 8,
		"level": 3,
		"rulesText": "SUNRISE: Migrate: Shed 2 cards and move this species to any legal spot on the board (this movement does not start a Turf War).",
		"flavorText": "",
		"image": null,
	},
	"SAM9": {
		"name": "Madagascar Fish Eagle",
		"pack": "Madagascar",
		"number": 30,
		"cardType": "Species",
		"speciesType": "Bird",
		"speciesName": "Haliaeetus vociferoides",
		"rarity": "Vanishing",
		"borders": {
			"left": ["red", "purple"],
			"right": ["purple", "red"],
			"top": [],
			"bottom": ["red", "purple"],
		},
		"energy": 14,
		"points": 12,
		"level": 4,
		"rulesText": "",
		"flavorText": "Close relative of the bald eagle - one of the most endangered raptors in the world. Loud, measured call: Wha ... wah ... wah ...",
		"image": null,
	},
	"SAM10": {
		"name": "Madagascar - Hotspot",
		"pack": "Madagascar",
		"number": 116,
		"cardType": "Hotspot",
		"speciesType": "",
		"speciesName": "",
		"rarity": "",
		"borders": {
			"top": ["blue"],
			"bottom": ["blue"],
			"left": ["blue"],
			"right": ["blue"]
		},
		"energy": 0,
		"points": 0,
		"level": 0,
		"rulesText": "",
		"flavorText": "",
		"image": null,
	}
};

module.exports = deckSample;